version: '3.8'
services:
  node-api:
    build: .
    image: node-api
    container_name: node-api
    restart: "always"
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
    environment:
      NODE_ENV: development
    network_mode: "host"
